// This file is auto-generated by TanStack Router
// It's used for type-safe routing in TypeScript projects
// For now, we'll keep it as a placeholder since we're using JavaScript

/* eslint-disable */

export {};
